import {
  PATTERN_CARD_IDS,
  type MatchSupport,
  type AutomationSupport,
  type PatternCardDefinition,
  type PatternCardInput,
  type PatternCardId,
  type PatternCategory,
  type PatternCollectionId,
  type PatternKind,
  type PatternMatcherDefinition,
  type PatternRuleBinding,
  type RuleFamilyId,
  type TalibPatternFunction,
} from './types';
import { hasValidRuleBindingParameters } from './rule-parameters';
import { ADDITIONAL_STRUCTURE_CARD_DEFINITIONS } from './structure-catalog';
import { TALIB_BATCH_1_CARD_DEFINITIONS } from './talib-batch-1';
import { TALIB_BATCH_2_CARD_DEFINITIONS } from './talib-batch-2';
import { TALIB_BATCH_3_CARD_DEFINITIONS } from './talib-batch-3';
import { TALIB_BATCH_4_CARD_DEFINITIONS } from './talib-batch-4';
export { PATTERN_COLLECTIONS } from './collections';

const SINGLE_LESSON = ['/chapters/09-single-candlestick-signals'] as const;
const MULTI_LESSON = ['/chapters/10-two-three-candlestick-patterns'] as const;
const STRUCTURE_LESSON = ['/chapters/11-consolidation-reversal-continuation-patterns'] as const;
const VOLUME_LESSON = ['/chapters/12-volume-price-liquidity-failed-signals'] as const;

const TALIB_FUNCTION_BY_CARD: Readonly<Partial<Record<PatternCardId, TalibPatternFunction>>> = {
  doji: 'CDLDOJI',
  hammer: 'CDLHAMMER',
  'shooting-star': 'CDLSHOOTINGSTAR',
  'bullish-engulfing': 'CDLENGULFING',
  'bearish-engulfing': 'CDLENGULFING',
  'bullish-harami': 'CDLHARAMI',
  'bearish-harami': 'CDLHARAMI',
  'piercing-line': 'CDLPIERCING',
  'dark-cloud-cover': 'CDLDARKCLOUDCOVER',
  'morning-star': 'CDLMORNINGSTAR',
  'evening-star': 'CDLEVENINGSTAR',
  'three-advancing-candles': 'CDL3WHITESOLDIERS',
  'three-falling-candles': 'CDL3BLACKCROWS',
  'talib-two-crows': 'CDL2CROWS',
  'talib-three-inside': 'CDL3INSIDE',
  'talib-three-line-strike': 'CDL3LINESTRIKE',
  'talib-three-outside': 'CDL3OUTSIDE',
  'talib-three-stars-in-the-south': 'CDL3STARSINSOUTH',
  'talib-abandoned-baby': 'CDLABANDONEDBABY',
  'talib-advance-block': 'CDLADVANCEBLOCK',
  'talib-belt-hold': 'CDLBELTHOLD',
  'talib-breakaway': 'CDLBREAKAWAY',
  'talib-closing-marubozu': 'CDLCLOSINGMARUBOZU',
  'talib-concealing-baby-swallow': 'CDLCONCEALBABYSWALL',
  'talib-counterattack': 'CDLCOUNTERATTACK',
  'talib-doji-star': 'CDLDOJISTAR',
  'talib-dragonfly-doji': 'CDLDRAGONFLYDOJI',
  'talib-evening-doji-star': 'CDLEVENINGDOJISTAR',
  'talib-gap-side-by-side-white-lines': 'CDLGAPSIDESIDEWHITE',
  'talib-gravestone-doji': 'CDLGRAVESTONEDOJI',
  'talib-hanging-man': 'CDLHANGINGMAN',
  'talib-harami-cross': 'CDLHARAMICROSS',
  'talib-high-wave': 'CDLHIGHWAVE',
  'talib-hikkake': 'CDLHIKKAKE',
  'talib-modified-hikkake': 'CDLHIKKAKEMOD',
  'talib-homing-pigeon': 'CDLHOMINGPIGEON',
  'talib-identical-three-crows': 'CDLIDENTICAL3CROWS',
  'talib-in-neck': 'CDLINNECK',
  'talib-inverted-hammer': 'CDLINVERTEDHAMMER',
  'talib-kicking': 'CDLKICKING',
  'talib-kicking-by-length': 'CDLKICKINGBYLENGTH',
  'talib-ladder-bottom': 'CDLLADDERBOTTOM',
  'talib-long-legged-doji': 'CDLLONGLEGGEDDOJI',
  'talib-long-line': 'CDLLONGLINE',
  'talib-marubozu': 'CDLMARUBOZU',
  'talib-matching-low': 'CDLMATCHINGLOW',
  'talib-mat-hold': 'CDLMATHOLD',
  'talib-morning-doji-star': 'CDLMORNINGDOJISTAR',
  'talib-on-neck': 'CDLONNECK',
  'talib-rickshaw-man': 'CDLRICKSHAWMAN',
  'talib-rise-fall-three-methods': 'CDLRISEFALL3METHODS',
  'talib-separating-lines': 'CDLSEPARATINGLINES',
  'talib-short-line': 'CDLSHORTLINE',
  'talib-spinning-top': 'CDLSPINNINGTOP',
  'talib-stalled-pattern': 'CDLSTALLEDPATTERN',
  'talib-stick-sandwich': 'CDLSTICKSANDWICH',
  'talib-takuri': 'CDLTAKURI',
  'talib-tasuki-gap': 'CDLTASUKIGAP',
  'talib-thrusting': 'CDLTHRUSTING',
  'talib-tristar': 'CDLTRISTAR',
  'talib-unique-three-river': 'CDLUNIQUE3RIVER',
  'talib-upside-gap-two-crows': 'CDLUPSIDEGAP2CROWS',
  'talib-x-side-gap-three-methods': 'CDLXSIDEGAP3METHODS',
};

type TalibTeachingMetadata = Pick<
  PatternCardDefinition,
  | 'minimumBars'
  | 'maximumBars'
  | 'patternDirection'
  | 'patternPurpose'
  | 'geometrySteps'
  | 'relatedPatternIds'
  | 'confirmationGuidance'
  | 'talibObservableDefinition'
  | 'talibDataRequirements'
>;

const TALIB_TEACHING_METADATA_BY_CARD: Readonly<
  Partial<Record<PatternCardId, TalibTeachingMetadata>>
> = {
  hammer: {
    minimumBars: 1,
    maximumBars: 1,
    patternDirection: 'bullish',
    patternPurpose: 'reversal',
    geometrySteps: ['目標 K 為 BodyShort 小實體。', '下影大於 ShadowLong、上影小於 ShadowVeryShort。', '實體低端不高於前一根低點加 Near 門檻。'],
    relatedPatternIds: ['talib-hanging-man', 'talib-dragonfly-doji'],
    confirmationGuidance: ['核對相對前一根低點的位置與三組 CandleSettings。', '下行背景需另行確認，官方函式本身不判斷趨勢。'],
    talibObservableDefinition: '目標 K 為 BodyShort 小實體、下影長於 ShadowLong、上影短於 ShadowVeryShort；實體低端不高於前一根低點加 Near 門檻。',
    talibDataRequirements: ['一根目標完成 K 與前一根低點', 'BodyShort、ShadowLong、ShadowVeryShort、Near 的前置平均；官方預設 lookback 11 根', '一致的 OHLC 價格模式與公司行動核對'],
  },
  'bullish-engulfing': {
    minimumBars: 2,
    maximumBars: 2,
    patternDirection: 'bullish',
    patternPurpose: 'reversal',
    geometrySteps: ['第一根為非零下跌實體。', '第二根為上漲實體並包住第一根實體。', '兩端嚴格超越回傳 +100；一端相等回傳 +80。'],
    relatedPatternIds: ['bearish-engulfing', 'talib-three-outside'],
    confirmationGuidance: ['只比較實體端點，不把影線納入。', '函式不判斷前段趨勢；背景與後續失效分開記錄。'],
    talibObservableDefinition: '第一根為非零下跌實體；第二根為上漲實體並以實體端點包住第一根。兩端嚴格超越回傳 +100，一端相等回傳 +80。',
    talibDataRequirements: ['兩根完成 K；官方固定 lookback 2 根', '不使用 CandleSettings', '一致的 OHLC 價格模式與公司行動核對'],
  },
  'bearish-engulfing': {
    minimumBars: 2,
    maximumBars: 2,
    patternDirection: 'bearish',
    patternPurpose: 'reversal',
    geometrySteps: ['第一根為非零上漲實體。', '第二根為下跌實體並包住第一根實體。', '兩端嚴格超越回傳 -100；一端相等回傳 -80。'],
    relatedPatternIds: ['bullish-engulfing', 'talib-three-outside'],
    confirmationGuidance: ['只比較實體端點，不把影線納入。', '函式不判斷前段趨勢；背景與後續失效分開記錄。'],
    talibObservableDefinition: '第一根為非零上漲實體；第二根為下跌實體並以實體端點包住第一根。兩端嚴格超越回傳 -100，一端相等回傳 -80。',
    talibDataRequirements: ['兩根完成 K；官方固定 lookback 2 根', '不使用 CandleSettings', '一致的 OHLC 價格模式與公司行動核對'],
  },
  'bullish-harami': {
    minimumBars: 2,
    maximumBars: 2,
    patternDirection: 'bullish',
    patternPurpose: 'reversal',
    geometrySteps: ['第一根為 BodyLong 長下跌實體。', '第二根為 BodyShort 短實體，完整落在第一根實體內。', '嚴格包含回傳 +100；一端相等回傳 +80。'],
    relatedPatternIds: ['bearish-harami', 'talib-harami-cross', 'talib-homing-pigeon'],
    confirmationGuidance: ['用實體端點核對包含，不要求第二根影線也被包含。', '第二根顏色決定官方回傳方向，背景另行確認。'],
    talibObservableDefinition: '第一根為 BodyLong 長實體，第二根為 BodyShort 短實體且完整位於第一根實體內；嚴格包含回傳完整值，一端相等回傳較弱值。',
    talibDataRequirements: ['兩根目標完成 K', 'BodyLong、BodyShort 前置平均；官方預設 lookback 11 根', '一致的 OHLC 價格模式與公司行動核對'],
  },
  'bearish-harami': {
    minimumBars: 2,
    maximumBars: 2,
    patternDirection: 'bearish',
    patternPurpose: 'reversal',
    geometrySteps: ['第一根為 BodyLong 長上漲實體。', '第二根為 BodyShort 短實體，完整落在第一根實體內。', '嚴格包含回傳 -100；一端相等回傳 -80。'],
    relatedPatternIds: ['bullish-harami', 'talib-harami-cross'],
    confirmationGuidance: ['用實體端點核對包含，不要求第二根影線也被包含。', '第二根顏色決定官方回傳方向，背景另行確認。'],
    talibObservableDefinition: '第一根為 BodyLong 長實體，第二根為 BodyShort 短實體且完整位於第一根實體內；嚴格包含回傳完整值，一端相等回傳較弱值。',
    talibDataRequirements: ['兩根目標完成 K', 'BodyLong、BodyShort 前置平均；官方預設 lookback 11 根', '一致的 OHLC 價格模式與公司行動核對'],
  },
  doji: {
    minimumBars: 1,
    maximumBars: 1,
    patternDirection: 'neutral',
    patternPurpose: 'indecision',
    geometrySteps: ['使用一根完成 K。', '開盤與收盤落在適用比較單位的近似相等範圍內。', '上下影線長度不決定是否為一般十字線。'],
    relatedPatternIds: ['relative-small-body', 'talib-belt-hold'],
    confirmationGuidance: ['先核對資料精度與價格升降單位，再判定開收是否近似。', '位置與後續條件另行記錄，不用十字外觀自行宣告反轉。'],
    talibObservableDefinition: '一根完成 K 的開收差，小於或等於 TA-Lib BodyDoji CandleSettings 依近期 K 線計算的平均門檻。',
    talibDataRequirements: ['一根目標完成 K', '足以計算 BodyDoji 近期平均的前置 K 線', '一致的 OHLC 價格模式與公司行動核對'],
  },
  'dark-cloud-cover': {
    minimumBars: 2,
    maximumBars: 2,
    patternDirection: 'bearish',
    patternPurpose: 'reversal',
    geometrySteps: ['第一根為相對長上漲實體。', '第二根下跌且開盤高於第一根最高價。', '第二根收進第一根實體並穿越指定百分比，預設為中點。'],
    relatedPatternIds: ['piercing-line', 'talib-counterattack'],
    confirmationGuidance: ['等待第二根完成收盤並核對穿越比例。', '前段上行背景與後續失效條件須分開列示。'],
    talibObservableDefinition: '第一根為長上漲實體；第二根為下跌實體，開盤高於第一根最高價，收盤深入第一根實體且超過 penetration 門檻，但仍高於第一根開盤。',
    talibDataRequirements: ['兩根目標完成 K', '足以計算 BodyLong 近期平均的前置 K 線', '呼叫端指定的 penetration 參數；TA-Lib 預設為 0.5'],
  },
  'three-advancing-candles': {
    minimumBars: 3,
    maximumBars: 3,
    patternDirection: 'bullish',
    patternPurpose: 'reversal',
    geometrySteps: ['三根皆為上漲實體且收盤依序提高。', '後兩根開盤位於前一根實體內或附近。', '實體不能過短，上影需相對短，後續實體不可明顯衰退。'],
    relatedPatternIds: ['three-falling-candles', 'talib-advance-block'],
    confirmationGuidance: ['核對三根實體、上影與開收順序均符合設定。', '完成只代表幾何候選，仍須檢查位置、量價與失效條件。'],
    talibObservableDefinition: '三根上漲 K 的收盤依序提高；後兩根開在前根實體內或附近，實體不短、上影相對短，且後續實體不可明顯縮短。',
    talibDataRequirements: ['三根目標完成 K', '足以計算 BodyShort、ShadowVeryShort、Near 與 Far CandleSettings 的前置 K 線', '一致的 OHLC 價格模式與公司行動核對'],
  },
  'three-falling-candles': {
    minimumBars: 3,
    maximumBars: 3,
    patternDirection: 'bearish',
    patternPurpose: 'reversal',
    geometrySteps: ['三根皆為下跌實體且收盤依序降低。', '後兩根開盤位於前一根實體內或附近。', '三根下影都相對短，實體不能短到失去推進意義。'],
    relatedPatternIds: ['three-advancing-candles', 'talib-three-stars-in-the-south'],
    confirmationGuidance: ['核對三根實體、下影與開收順序均符合設定。', '完成只代表幾何候選，仍須檢查位置、量價與失效條件。'],
    talibObservableDefinition: '前一根為上漲 K，接著三根下跌 K 收盤依序降低；三根開盤位於前根實體內，且三根下影皆相對短。',
    talibDataRequirements: ['前三黑鴉之前一根 K，加上三根目標完成 K', '足以計算 ShadowVeryShort CandleSettings 的前置 K 線', '一致的 OHLC 價格模式與公司行動核對'],
  },
  'evening-star': {
    minimumBars: 3,
    maximumBars: 3,
    patternDirection: 'bearish',
    patternPurpose: 'reversal',
    geometrySteps: ['第一根為 BodyLong 長上漲實體。', '第二根為 BodyShort 小實體且向上實體跳空。', '第三根為大於 BodyShort 的下跌實體，收盤達 penetration 深度。'],
    relatedPatternIds: ['morning-star', 'talib-evening-doji-star'],
    confirmationGuidance: ['等待第三根完成並核對 penetration，官方預設為 0.3。', '官方函式不判斷上行趨勢，背景需另行確認。'],
    talibObservableDefinition: '第一根為 BodyLong 長上漲實體；第二根為向上實體跳空的 BodyShort；第三根為大於 BodyShort 的下跌實體，收盤依 penetration 參數深入第一根實體。',
    talibDataRequirements: ['三根目標完成 K', 'BodyLong、BodyShort 前置平均與 penetration 參數；官方預設 lookback 12 根、penetration 0.3', '一致的 OHLC 價格模式與公司行動核對'],
  },
  'morning-star': {
    minimumBars: 3,
    maximumBars: 3,
    patternDirection: 'bullish',
    patternPurpose: 'reversal',
    geometrySteps: ['第一根為 BodyLong 長下跌實體。', '第二根為 BodyShort 小實體且整個實體向下跳空。', '第三根為大於 BodyShort 的上漲實體，收盤達 penetration 深度。'],
    relatedPatternIds: ['evening-star', 'talib-morning-doji-star'],
    confirmationGuidance: ['等待第三根完成並核對 penetration，官方預設為 0.3。', '第二根不要求 Doji；若為 Doji 請對照晨星十字。'],
    talibObservableDefinition: '第一根 BodyLong 長下跌；第二根 BodyShort 小實體且整個實體向下跳空；第三根上漲且大於 BodyShort，收盤高於第一根收盤加實體乘 penetration。',
    talibDataRequirements: ['三根目標完成 K', 'BodyLong、BodyShort 前置平均與 penetration 參數；官方預設 lookback 12 根、penetration 0.3', '一致價格模式與公司行動核對'],
  },
  'piercing-line': {
    minimumBars: 2,
    maximumBars: 2,
    patternDirection: 'bullish',
    patternPurpose: 'reversal',
    geometrySteps: ['第一根為 BodyLong 長下跌。', '第二根為長上漲 K，開盤低於前低。', '第二根收盤高於第一根實體中點，但低於第一根開盤。'],
    relatedPatternIds: ['dark-cloud-cover', 'talib-in-neck', 'talib-on-neck'],
    confirmationGuidance: ['官方 penetration 固定為 0.5，不是呼叫參數。', '下行背景需另行確認。'],
    talibObservableDefinition: '第一根 BodyLong 長下跌；第二根長上漲且開盤低於前低，收盤低於第一根開盤但高於第一根下跌實體中點。',
    talibDataRequirements: ['兩根目標完成 K', 'BodyLong 前置平均；官方預設 lookback 11 根', '固定 0.5 中點門檻與一致價格模式'],
  },
  'shooting-star': {
    minimumBars: 1,
    maximumBars: 1,
    patternDirection: 'bearish',
    patternPurpose: 'reversal',
    geometrySteps: ['目標 K 為 BodyShort 小實體。', '上影大於 ShadowLong、下影小於 ShadowVeryShort。', '目標整個實體嚴格高於前一根實體。'],
    relatedPatternIds: ['talib-inverted-hammer', 'hammer', 'talib-hanging-man'],
    confirmationGuidance: ['核對目標實體相對前一根實體的 gap。', '上行背景需另行確認。'],
    talibObservableDefinition: '目標 K 為 BodyShort 小實體、上影長於 ShadowLong、下影短於 ShadowVeryShort，且目標實體最低端嚴格高於前一根實體最高端。',
    talibDataRequirements: ['一根目標 K 與前一根實體', 'BodyShort、ShadowLong、ShadowVeryShort；官方預設 lookback 11 根', '一致價格模式與公司行動核對'],
  },
};

function kindFor(category: PatternCategory, support: MatchSupport): PatternKind {
  if (support === 'guardrail') {
    return 'guardrail';
  }
  if (category === '結構型態') {
    return 'chart-pattern';
  }
  if (category === '量價、流動性與守門') {
    return 'market-observation';
  }
  return 'candlestick-pattern';
}

function automationSupportFor(support: MatchSupport): AutomationSupport {
  if (support === 'mvp') {
    return 'short-window';
  }
  return support === 'guardrail' ? 'guardrail' : 'teaching-only';
}

function collectionsFor(
  kind: PatternKind,
  talibFunction: TalibPatternFunction | undefined,
): readonly PatternCollectionId[] {
  if (kind === 'candlestick-pattern') {
    return talibFunction
      ? ['candlestick-reference', 'talib-advanced']
      : ['candlestick-reference'];
  }
  return ['price-structure'];
}

function binding(
  ruleId: string,
  group: PatternRuleBinding['group'],
  weight: number,
  teachingLabel: string,
  parameters: PatternRuleBinding['parameters'] = {},
): PatternRuleBinding {
  return { ruleId, group, weight, teachingLabel, parameters };
}

function mvpMatcher(
  ruleFamilyId: RuleFamilyId,
  minimumBars: number,
  minimumScore: number,
  required: Pick<PatternRuleBinding, 'ruleId' | 'teachingLabel' | 'parameters'>,
  context: Pick<PatternRuleBinding, 'ruleId' | 'teachingLabel' | 'parameters'>,
  supporting: Pick<PatternRuleBinding, 'ruleId' | 'teachingLabel' | 'parameters'>,
  invalidating: Pick<PatternRuleBinding, 'ruleId' | 'teachingLabel' | 'parameters'>,
): PatternMatcherDefinition {
  return {
    ruleFamilyId,
    minimumBars,
    minimumScore,
    rules: [
      binding(required.ruleId, 'required', 50, required.teachingLabel, required.parameters),
      binding(context.ruleId, 'context', 30, context.teachingLabel, context.parameters),
      binding(supporting.ruleId, 'supporting', 20, supporting.teachingLabel, supporting.parameters),
      binding(invalidating.ruleId, 'invalidating', 0, invalidating.teachingLabel, invalidating.parameters),
    ],
  };
}

function card(definition: PatternCardInput): PatternCardDefinition {
  const kind = kindFor(definition.category, definition.matchSupport);
  const talibFunction = TALIB_FUNCTION_BY_CARD[definition.id];
  const teachingMetadata = TALIB_TEACHING_METADATA_BY_CARD[definition.id];
  const officialSources = talibFunction
    ? [
        `TA-Lib 官方 Pattern Recognition Functions｜${talibFunction}`,
        `TA-Lib Core C 原始碼｜ta_${talibFunction}.c`,
      ]
    : [];
  return {
    ...definition,
    ...teachingMetadata,
    slug: definition.slug ?? definition.id,
    kind,
    automationSupport: definition.automationSupport ?? automationSupportFor(definition.matchSupport),
    collections: collectionsFor(kind, talibFunction),
    sourceNotes: [...definition.sourceNotes, ...officialSources],
    ...(talibFunction
      ? {
          talibFunction,
          talibImplementationSupport: 'teaching-only' as const,
          talibObservableDefinition:
            teachingMetadata?.talibObservableDefinition ?? definition.observableDefinition,
          talibDataRequirements:
            teachingMetadata?.talibDataRequirements ?? definition.dataRequirements,
        }
      : {}),
  };
}

function sourceNote(section: string, row: string): readonly string[] {
  return [`附錄 A｜${section}｜${row}`];
}

const commonLimitations = [
  '型態名稱只協助整理可觀察條件，不構成未來價格的預測或任何交易建議。',
  '必須先固定週期、價格模式、資料精度與比較窗，不能跨標的或跨週期直接比較。',
] as const;

/**
 * 供型態卡 UI 與後續規則引擎共用的唯一型態清冊。
 * 未列為 mvp 的結構、量價與守門卡只用於教學，不能被第一版 matcher 假裝辨識。
 */
export const PATTERN_CARDS: readonly PatternCardDefinition[] = [
  card({
    id: 'relative-long-body',
    nameZhTw: '相對長實體',
    nameEn: 'Relative long real body',
    aliases: ['長實體', '相對大實體'],
    category: '單根與描述型',
    matchSupport: 'mvp',
    sourceRow: '相對長實體／相對小實體',
    sourceNotes: sourceNote('單根 K 線', '相對長實體／相對小實體'),
    oneSentenceMeaning: '描述目標 K 的非零實體在固定回看窗中相對突出，仍須連同位置與背景閱讀。',
    observableDefinition: '同標的、同週期前 20 根完成 K 的非零實體為比較窗；目標實體位於上四分位。',
    dataRequirements: ['至少 21 根完成 K 線', '前 20 根中足夠的非零實體', '同一價格模式與比較單位'],
    background: ['說明它發生的位置、前段結構與量價關係。', '把比較窗排除目標 K，避免用自己抬高自己的相對性。'],
    commonMisreads: ['把長實體當成固定百分比。', '只看實體大小就替後續價格下結論。'],
    invalidationGuidance: ['比較窗不足或混用不同週期時，不應給出相對長實體判讀。', '資料精度或價格模式未核對時，先停在資料限制。'],
    limitations: commonLimitations,
    lessonLinks: SINGLE_LESSON,
    matcher: mvpMatcher(
      'relative-body-size',
      21,
      60,
      { ruleId: 'relative-body-upper-quartile', teachingLabel: '目標實體位於前 20 根比較窗的上四分位', parameters: { comparisonWindow: 20, percentile: 0.75, targetExcluded: true } },
      { ruleId: 'same-window-context', teachingLabel: '比較窗固定為同標的、同週期的已完成 K 線', parameters: { comparisonWindow: 20, targetExcluded: true } },
      { ruleId: 'position-and-volume-recorded', teachingLabel: '位置與量價背景可供讀者核對', parameters: { requiredFields: 'position-volume' } },
      { ruleId: 'relative-window-unavailable', teachingLabel: '非零實體比較窗不足時不評分', parameters: { minimumPriorBodies: 20 } },
    ),
  }),
  card({
    id: 'relative-small-body',
    nameZhTw: '相對小實體',
    nameEn: 'Relative small real body',
    aliases: ['小實體', '相對短實體'],
    category: '單根與描述型',
    matchSupport: 'mvp',
    sourceRow: '相對長實體／相對小實體',
    sourceNotes: sourceNote('單根 K 線', '相對長實體／相對小實體'),
    oneSentenceMeaning: '描述目標 K 的非零實體在固定回看窗中相對小，不能單獨等同於猶豫或反轉。',
    observableDefinition: '同標的、同週期前 20 根完成 K 的非零實體為比較窗；目標實體位於下四分位。',
    dataRequirements: ['至少 21 根完成 K 線', '前 20 根中足夠的非零實體', '同一價格模式與比較單位'],
    background: ['先定位在趨勢、區間或關鍵區域中的位置。', '把成交量與後續可驗證條件分開記錄。'],
    commonMisreads: ['把任何短實體都稱為十字線。', '把小實體直接解讀成參與者心理。'],
    invalidationGuidance: ['比較窗不足、資料尚未完成或價格精度不明時，不輸出相對小實體。', '若實體為零，應改由十字線規則處理。'],
    limitations: commonLimitations,
    lessonLinks: SINGLE_LESSON,
    matcher: mvpMatcher(
      'relative-body-size',
      21,
      60,
      { ruleId: 'relative-body-lower-quartile', teachingLabel: '目標實體位於前 20 根比較窗的下四分位', parameters: { comparisonWindow: 20, percentile: 0.25, targetExcluded: true } },
      { ruleId: 'same-window-context', teachingLabel: '比較窗固定為同標的、同週期的已完成 K 線', parameters: { comparisonWindow: 20, targetExcluded: true } },
      { ruleId: 'position-and-volume-recorded', teachingLabel: '位置與量價背景可供讀者核對', parameters: { requiredFields: 'position-volume' } },
      { ruleId: 'relative-window-unavailable', teachingLabel: '非零實體比較窗不足時不評分', parameters: { minimumPriorBodies: 20 } },
    ),
  }),
  card({
    id: 'doji',
    nameZhTw: '十字線',
    nameEn: 'Doji',
    aliases: ['十字 K', '開收近似'],
    category: '單根與描述型',
    matchSupport: 'mvp',
    sourceRow: '十字線',
    sourceNotes: sourceNote('單根 K 線', '十字線'),
    oneSentenceMeaning: '開收接近的形狀描述當日價格位置，需要背景與後續資料才有可討論的意義。',
    observableDefinition: '開收差距不超過適用的一個價格升降單位或來源四捨五入單位。',
    dataRequirements: ['一根完成 K 線', '可驗證的比較單位或來源精度', '已知時間週期'],
    background: ['記錄它是否在關鍵區域、趨勢尾端或區間中央。', '後續確認不應被當成當下已知的事實。'],
    commonMisreads: ['看到十字線就宣布反轉。', '忽略資料四捨五入造成的開收相等。'],
    invalidationGuidance: ['比較單位缺失時，開收近似不能可靠判定。', '若 K 線尚未完成，不應把盤中形狀當成收盤結果。'],
    limitations: commonLimitations,
    lessonLinks: SINGLE_LESSON,
    matcher: mvpMatcher(
      'doji',
      1,
      60,
      { ruleId: 'open-close-within-comparison-unit', teachingLabel: '開收差距不超過一個適用比較單位', parameters: { maximumUnits: 1 } },
      { ruleId: 'location-context-recorded', teachingLabel: '位置與前段結構可供讀者核對', parameters: { needsLocation: true } },
      { ruleId: 'follow-up-not-assumed', teachingLabel: '後續確認不會被當成當下證據', parameters: { noLookAhead: true } },
      { ruleId: 'incomplete-or-imprecise-bar', teachingLabel: '未完成或比較單位缺失時不評分', parameters: { requiresComparisonUnit: true } },
    ),
  }),
  card({
    id: 'hammer',
    nameZhTw: '錘子形',
    nameEn: 'Hammer',
    aliases: ['錘頭線', '長下影錘子形'],
    category: '單根與描述型',
    matchSupport: 'mvp',
    sourceRow: '錘子形',
    sourceNotes: sourceNote('單根 K 線', '錘子形'),
    oneSentenceMeaning: '長下影且實體靠近當日高位的幾何描述，必須放在下行背景與支撐候選中核對。',
    observableDefinition: '令 B_L=min(O,C)、B_H=max(O,C)、R=H-L>0、u=max(|C-O|,比較單位)：B_L≥L+2R/3、B_L-L≥2u、H-B_H≤u。',
    dataRequirements: ['一根完成且高低不同的 K 線', '適用比較單位', '可查核的前段結構與區域'],
    background: ['優先檢查前段是否下行與是否接近支撐候選。', '量價關係與觸發、失效條件要分開列出。'],
    commonMisreads: ['名稱一出現就直接下單。', '只看長下影線，忽略實體位置與上影線。'],
    invalidationGuidance: ['前段未下行、實體位置不符或影線比例不符時，不成立。', '低流動性或資料未完成時，保留為待核對而非候選。'],
    limitations: commonLimitations,
    lessonLinks: SINGLE_LESSON,
    matcher: mvpMatcher(
      'single-candle-wick-geometry',
      1,
      70,
      { ruleId: 'hammer-wick-geometry', teachingLabel: '實體靠近高位、下影至少為有效實體兩倍且上影受比較單位限制', parameters: { bodyLowMinimumRange: 0.6667, lowerWickBodyMultiple: 2, upperWickMaximumUnits: 1 } },
      { ruleId: 'prior-structure-falling', teachingLabel: '前段結構可辨識為下行背景', parameters: { expected: 'falling' } },
      { ruleId: 'support-zone-or-volume-context', teachingLabel: '支撐候選與量價背景可供核對', parameters: { needs: 'support-volume' } },
      { ruleId: 'invalid-single-candle-data', teachingLabel: '範圍為零、比較單位缺失或資料未完成時不評分', parameters: { requiresRange: true, requiresComparisonUnit: true } },
    ),
  }),
  card({
    id: 'shooting-star',
    nameZhTw: '射擊之星形',
    nameEn: 'Shooting star',
    aliases: ['流星線', '長上影射擊之星'],
    category: '單根與描述型',
    matchSupport: 'mvp',
    sourceRow: '射擊之星形',
    sourceNotes: sourceNote('單根 K 線', '射擊之星形'),
    oneSentenceMeaning: '長上影且實體靠近當日低位的幾何描述，必須放在上行背景與壓力候選中核對。',
    observableDefinition: '令 B_L=min(O,C)、B_H=max(O,C)、R=H-L>0、u=max(|C-O|,比較單位)：B_H≤L+R/3、H-B_H≥2u、B_L-L≤u。',
    dataRequirements: ['一根完成且高低不同的 K 線', '適用比較單位', '可查核的前段結構與區域'],
    background: ['優先檢查前段是否上行與是否接近壓力候選。', '量價關係、觸發與失效須由讀者另行核對。'],
    commonMisreads: ['用長上影線推論必定下跌。', '忽略實體位置、下影限制與資料精度。'],
    invalidationGuidance: ['前段未上行、影線比例不符或資料未完成時，不成立。', '資料不足只能標示可觀察條件不足。'],
    limitations: commonLimitations,
    lessonLinks: SINGLE_LESSON,
    matcher: mvpMatcher(
      'single-candle-wick-geometry',
      1,
      70,
      { ruleId: 'shooting-star-wick-geometry', teachingLabel: '實體靠近低位、上影至少為有效實體兩倍且下影受比較單位限制', parameters: { bodyHighMaximumRange: 0.3333, upperWickBodyMultiple: 2, lowerWickMaximumUnits: 1 } },
      { ruleId: 'prior-structure-rising', teachingLabel: '前段結構可辨識為上行背景', parameters: { expected: 'rising' } },
      { ruleId: 'resistance-zone-or-volume-context', teachingLabel: '壓力候選與量價背景可供核對', parameters: { needs: 'resistance-volume' } },
      { ruleId: 'invalid-single-candle-data', teachingLabel: '範圍為零、比較單位缺失或資料未完成時不評分', parameters: { requiresRange: true, requiresComparisonUnit: true } },
    ),
  }),
  card({
    id: 'near-marubozu',
    nameZhTw: '近似光頭光腳',
    nameEn: 'Near marubozu',
    aliases: ['近似無影線', '光頭光腳'],
    category: '單根與描述型',
    matchSupport: 'mvp',
    sourceRow: '近似光頭光腳',
    sourceNotes: sourceNote('單根 K 線', '近似光頭光腳'),
    oneSentenceMeaning: '上下影線都很短的形狀描述當日開收接近區間兩端，仍要看相對實體與所在位置。',
    observableDefinition: '上下影線各不超過一個適用價格升降單位或來源四捨五入單位。',
    dataRequirements: ['一根完成 K 線', '適用比較單位', '同一價格模式'],
    background: ['配合相對實體大小、位置、跳空與量價關係閱讀。', '把可用價格空間與失效距離另列，不從形狀推導保證。'],
    commonMisreads: ['把無影線當成不可逆轉的強弱。', '忽略價格升降單位與來源精度。'],
    invalidationGuidance: ['任一影線超出容忍值時不成立。', '比較單位不明時，不能可靠稱為近似光頭光腳。'],
    limitations: commonLimitations,
    lessonLinks: SINGLE_LESSON,
    matcher: mvpMatcher(
      'near-marubozu',
      1,
      65,
      { ruleId: 'both-wicks-within-comparison-unit', teachingLabel: '上下影線各不超過一個適用比較單位', parameters: { maximumUnits: 1 } },
      { ruleId: 'relative-body-context-recorded', teachingLabel: '相對實體大小與位置可供核對', parameters: { needs: 'relative-body-position' } },
      { ruleId: 'volume-and-gap-context-recorded', teachingLabel: '量價與跳空背景可供核對', parameters: { needs: 'volume-gap' } },
      { ruleId: 'comparison-unit-unavailable', teachingLabel: '比較單位缺失時不評分', parameters: { requiresComparisonUnit: true } },
    ),
  }),
  card({
    id: 'close-rejection-indecision',
    nameZhTw: '收盤位置／拒絕／猶豫',
    nameEn: 'Close location, rejection, and indecision',
    aliases: ['收盤位置', '長影拒絕', '猶豫 K'],
    category: '單根與描述型',
    matchSupport: 'mvp',
    sourceRow: '收盤位置／拒絕／猶豫',
    sourceNotes: sourceNote('單根 K 線', '收盤位置／拒絕／猶豫'),
    oneSentenceMeaning: '把收盤位置、較長影線與小實體分開描述，避免把形狀詞彙誤當成因果說明。',
    observableDefinition: '收盤位置=(C-L)/(H-L)；較長影線表示盤中離開後收回較近位置，小實體或十字線表示開收接近。',
    dataRequirements: ['一根高低不同的完成 K 線', '比較單位', '指定的日內範圍'],
    background: ['先指定比較窗、位置與後續資料可得性。', '將「拒絕」保留為描述詞，不擴寫成參與者意圖。'],
    commonMisreads: ['把描述詞當成主力心理或方向結論。', '未分開收盤位置、影線與小實體的條件。'],
    invalidationGuidance: ['範圍為零時，收盤位置與影線比例不可用。', '比較單位或資料精度不明時，僅能提示需要核對。'],
    limitations: commonLimitations,
    lessonLinks: SINGLE_LESSON,
    matcher: mvpMatcher(
      'candle-descriptors',
      1,
      60,
      { ruleId: 'close-location-or-wick-descriptor', teachingLabel: '收盤位置、長影線或小實體符合已設定的描述門檻', parameters: { closeLocationLow: 0.3333, closeLocationHigh: 0.6667, wickBodyMultiple: 2 } },
      { ruleId: 'location-context-recorded', teachingLabel: '關鍵區域與前段結構可供核對', parameters: { needsLocation: true } },
      { ruleId: 'descriptor-language-limited', teachingLabel: '說明維持在可觀察描述，不加入因果推論', parameters: { descriptiveOnly: true } },
      { ruleId: 'range-or-unit-unavailable', teachingLabel: '範圍為零或比較單位缺失時不評分', parameters: { requiresRange: true, requiresComparisonUnit: true } },
    ),
  }),
  card({
    id: 'bullish-engulfing',
    nameZhTw: '多頭外包線',
    nameEn: 'Bullish engulfing',
    aliases: ['多方外包', '多頭吞沒'],
    category: '雙根與三根組合',
    matchSupport: 'mvp',
    sourceRow: '多頭外包線／空頭外包線',
    sourceNotes: sourceNote('雙根與三根組合', '多頭外包線／空頭外包線'),
    oneSentenceMeaning: '前根為下跌非零實體，當前上漲實體完整包含前根實體；影線不參與包含判定。',
    observableDefinition: '只比較兩根實體的開收範圍：前根與當前根方向相反且當前實體完整包含前根實體。',
    dataRequirements: ['至少兩根完成 K 線', '兩根非零實體', '同一價格模式與比較單位'],
    background: ['檢查下行背景、關鍵區域與量價關係。', '把觸發與失效距離和形狀本身分開記錄。'],
    commonMisreads: ['把影線包含關係當成外包線。', '只看顏色而未比較兩個實體邊界。'],
    invalidationGuidance: ['前根方向、實體包含關係或資料模式不符時不成立。', '右端資料未完成時不應命名。'],
    limitations: commonLimitations,
    lessonLinks: MULTI_LESSON,
    matcher: mvpMatcher(
      'engulfing-body',
      2,
      70,
      { ruleId: 'bullish-opposite-body-engulfing', teachingLabel: '下跌前實體被當前上漲實體完整包含，影線不參與', parameters: { direction: 'bullish', bodyOnly: true } },
      { ruleId: 'prior-structure-falling', teachingLabel: '前段結構可辨識為下行背景', parameters: { expected: 'falling' } },
      { ruleId: 'zone-or-volume-context', teachingLabel: '關鍵區域與量價背景可供核對', parameters: { needs: 'zone-volume' } },
      { ruleId: 'mixed-price-mode-or-incomplete-window', teachingLabel: '價格模式混用或 K 線未完成時不評分', parameters: { requiresRawPriceMode: true } },
    ),
  }),
  card({
    id: 'bearish-engulfing',
    nameZhTw: '空頭外包線',
    nameEn: 'Bearish engulfing',
    aliases: ['空方外包', '空頭吞沒'],
    category: '雙根與三根組合',
    matchSupport: 'mvp',
    sourceRow: '多頭外包線／空頭外包線',
    sourceNotes: sourceNote('雙根與三根組合', '多頭外包線／空頭外包線'),
    oneSentenceMeaning: '前根為上漲非零實體，當前下跌實體完整包含前根實體；影線不參與包含判定。',
    observableDefinition: '只比較兩根實體的開收範圍：前根與當前根方向相反且當前實體完整包含前根實體。',
    dataRequirements: ['至少兩根完成 K 線', '兩根非零實體', '同一價格模式與比較單位'],
    background: ['檢查上行背景、關鍵區域與量價關係。', '確認與失效條件必須事前寫下。'],
    commonMisreads: ['把影線包含關係當成外包線。', '把一根收低 K 線直接叫空頭外包線。'],
    invalidationGuidance: ['前根方向、實體包含關係或資料模式不符時不成立。', '右端資料未完成時不應命名。'],
    limitations: commonLimitations,
    lessonLinks: MULTI_LESSON,
    matcher: mvpMatcher(
      'engulfing-body',
      2,
      70,
      { ruleId: 'bearish-opposite-body-engulfing', teachingLabel: '上漲前實體被當前下跌實體完整包含，影線不參與', parameters: { direction: 'bearish', bodyOnly: true } },
      { ruleId: 'prior-structure-rising', teachingLabel: '前段結構可辨識為上行背景', parameters: { expected: 'rising' } },
      { ruleId: 'zone-or-volume-context', teachingLabel: '關鍵區域與量價背景可供核對', parameters: { needs: 'zone-volume' } },
      { ruleId: 'mixed-price-mode-or-incomplete-window', teachingLabel: '價格模式混用或 K 線未完成時不評分', parameters: { requiresRawPriceMode: true } },
    ),
  }),
  card({
    id: 'bullish-harami',
    nameZhTw: '多頭母子線',
    nameEn: 'Bullish harami',
    aliases: ['多頭內包', '多方母子'],
    category: '雙根與三根組合',
    matchSupport: 'mvp',
    sourceRow: '多頭母子線／空頭母子線',
    sourceNotes: sourceNote('雙根與三根組合', '多頭母子線／空頭母子線'),
    oneSentenceMeaning: '前根為相對長下跌實體，當前相反方向或小實體完整落在前根實體內。',
    observableDefinition: '前根以目標前 20 根比較窗確認相對長；當前實體完全位於前根實體邊界內，影線不作判定。',
    dataRequirements: ['至少 22 根完成 K 線', '前根以前 20 根可比較的非零實體', '兩根的實體資料'],
    background: ['先檢查下行背景、位置與確認條件。', '母子關係是實體關係，不是任意小 K 線。'],
    commonMisreads: ['把任何小 K 線都叫母子線。', '用影線而非實體判斷內包。'],
    invalidationGuidance: ['前根不相對長、當前實體越界或比較窗不足時不成立。', '價格模式不一致時先停止判讀。'],
    limitations: commonLimitations,
    lessonLinks: MULTI_LESSON,
    matcher: mvpMatcher(
      'harami-body',
      22,
      65,
      { ruleId: 'bullish-long-parent-contained-child', teachingLabel: '相對長下跌母實體包含當前小或上漲子實體', parameters: { parentPercentile: 0.75, comparisonWindow: 20, direction: 'bullish', bodyOnly: true } },
      { ruleId: 'prior-structure-falling', teachingLabel: '前段結構可辨識為下行背景', parameters: { expected: 'falling' } },
      { ruleId: 'position-and-confirmation-context', teachingLabel: '位置與確認條件可供核對', parameters: { needs: 'position-confirmation' } },
      { ruleId: 'harami-window-unavailable', teachingLabel: '相對長實體比較窗不足時不評分', parameters: { minimumPriorBodies: 20 } },
    ),
  }),
  card({
    id: 'bearish-harami',
    nameZhTw: '空頭母子線',
    nameEn: 'Bearish harami',
    aliases: ['空頭內包', '空方母子'],
    category: '雙根與三根組合',
    matchSupport: 'mvp',
    sourceRow: '多頭母子線／空頭母子線',
    sourceNotes: sourceNote('雙根與三根組合', '多頭母子線／空頭母子線'),
    oneSentenceMeaning: '前根為相對長上漲實體，當前相反方向或小實體完整落在前根實體內。',
    observableDefinition: '前根以目標前 20 根比較窗確認相對長；當前實體完全位於前根實體邊界內，影線不作判定。',
    dataRequirements: ['至少 22 根完成 K 線', '前根以前 20 根可比較的非零實體', '兩根的實體資料'],
    background: ['先檢查上行背景、位置與確認條件。', '內包需要寫清楚實體容忍值。'],
    commonMisreads: ['把任何小 K 線都叫母子線。', '忽略前根必須是相對長實體。'],
    invalidationGuidance: ['前根不相對長、當前實體越界或比較窗不足時不成立。', '價格模式不一致時先停止判讀。'],
    limitations: commonLimitations,
    lessonLinks: MULTI_LESSON,
    matcher: mvpMatcher(
      'harami-body',
      22,
      65,
      { ruleId: 'bearish-long-parent-contained-child', teachingLabel: '相對長上漲母實體包含當前小或下跌子實體', parameters: { parentPercentile: 0.75, comparisonWindow: 20, direction: 'bearish', bodyOnly: true } },
      { ruleId: 'prior-structure-rising', teachingLabel: '前段結構可辨識為上行背景', parameters: { expected: 'rising' } },
      { ruleId: 'position-and-confirmation-context', teachingLabel: '位置與確認條件可供核對', parameters: { needs: 'position-confirmation' } },
      { ruleId: 'harami-window-unavailable', teachingLabel: '相對長實體比較窗不足時不評分', parameters: { minimumPriorBodies: 20 } },
    ),
  }),
  card({
    id: 'piercing-line',
    nameZhTw: '穿透形',
    nameEn: 'Piercing line',
    aliases: ['多頭穿透線'],
    category: '雙根與三根組合',
    matchSupport: 'mvp',
    sourceRow: '穿透形',
    sourceNotes: sourceNote('雙根與三根組合', '穿透形'),
    oneSentenceMeaning: '前根下跌後，當前收盤穿越前根實體中點但未越過前根開盤的雙根條件。',
    observableDefinition: '當前開盤低於前根最低價或前收，收盤高於前根實體中點且低於前根開盤；使用固定缺口慣例。',
    dataRequirements: ['至少兩根完成 K 線', '兩根完整 OHLC 與比較單位', '候選窗內的公司行動資料'],
    background: ['先說明下行背景、位置、量價關係與確認。', '跳空與價格連續性要在原始價格資料中核對。'],
    commonMisreads: ['把一根收高 K 線稱為穿透形。', '未寫缺口慣例就比較兩根。'],
    invalidationGuidance: ['中點未穿越、開盤條件不符或公司行動影響連續性時不成立。', '原始價格與公司行動未核對時不評分。'],
    limitations: commonLimitations,
    lessonLinks: MULTI_LESSON,
    matcher: mvpMatcher(
      'midpoint-penetration',
      2,
      70,
      { ruleId: 'bullish-midpoint-penetration', teachingLabel: '下跌前根後，當前根依固定缺口慣例開低並收過前實體中點', parameters: { direction: 'bullish', requiresMidpoint: true, gapConvention: 'below-prior-low-or-close' } },
      { ruleId: 'prior-structure-falling', teachingLabel: '前段結構可辨識為下行背景', parameters: { expected: 'falling' } },
      { ruleId: 'zone-volume-and-confirmation-context', teachingLabel: '位置、量價與確認條件可供核對', parameters: { needs: 'zone-volume-confirmation' } },
      { ruleId: 'price-continuity-action-intersects-window', teachingLabel: '公司行動影響跳空或連續性時不評分', parameters: { requiresPriceContinuity: true } },
    ),
  }),
  card({
    id: 'dark-cloud-cover',
    nameZhTw: '烏雲形',
    nameEn: 'Dark cloud cover',
    aliases: ['烏雲蓋頂'],
    category: '雙根與三根組合',
    matchSupport: 'mvp',
    sourceRow: '烏雲形',
    sourceNotes: sourceNote('雙根與三根組合', '烏雲形'),
    oneSentenceMeaning: '前根上漲後，當前收盤跌破前根實體中點但未跌破前根開盤的雙根條件。',
    observableDefinition: '當前開盤高於前根最高價或前收，收盤低於前根實體中點且高於前根開盤；使用固定缺口慣例。',
    dataRequirements: ['至少兩根完成 K 線', '兩根完整 OHLC 與比較單位', '候選窗內的公司行動資料'],
    background: ['先說明上行背景、位置、量價關係與確認。', '跳空與價格連續性要在原始價格資料中核對。'],
    commonMisreads: ['把一根收低 K 線稱為烏雲形。', '未寫缺口慣例就比較兩根。'],
    invalidationGuidance: ['中點未跌破、開盤條件不符或公司行動影響連續性時不成立。', '原始價格與公司行動未核對時不評分。'],
    limitations: commonLimitations,
    lessonLinks: MULTI_LESSON,
    matcher: mvpMatcher(
      'midpoint-penetration',
      2,
      70,
      { ruleId: 'bearish-midpoint-penetration', teachingLabel: '上漲前根後，當前根依固定缺口慣例開高並收破前實體中點', parameters: { direction: 'bearish', requiresMidpoint: true, gapConvention: 'above-prior-high-or-close' } },
      { ruleId: 'prior-structure-rising', teachingLabel: '前段結構可辨識為上行背景', parameters: { expected: 'rising' } },
      { ruleId: 'zone-volume-and-confirmation-context', teachingLabel: '位置、量價與確認條件可供核對', parameters: { needs: 'zone-volume-confirmation' } },
      { ruleId: 'price-continuity-action-intersects-window', teachingLabel: '公司行動影響跳空或連續性時不評分', parameters: { requiresPriceContinuity: true } },
    ),
  }),
  card({
    id: 'morning-star',
    nameZhTw: '晨星形',
    nameEn: 'Morning star',
    aliases: ['晨星'],
    category: '雙根與三根組合',
    matchSupport: 'mvp',
    sourceRow: '晨星形',
    sourceNotes: sourceNote('雙根與三根組合', '晨星形'),
    oneSentenceMeaning: '相對長下跌實體、小實體或十字、以及收盤穿越第一根中點的上漲第三根，構成三根條件。',
    observableDefinition: '第一根為相對長下跌實體，第二根為小實體或十字，第三根上漲且收盤穿越第一根實體中點。',
    dataRequirements: ['至少 23 根完成 K 線', '第一根前 20 根比較窗', '三根完整 OHLC 與公司行動資料'],
    background: ['核對下行背景、第二根實體分離口徑、位置與確認。', '公司行動影響價格連續性時不能硬判缺口。'],
    commonMisreads: ['把任意三根上漲組合視為晨星。', '忽略第一根相對長與第三根中點穿越。'],
    invalidationGuidance: ['缺少中點穿越、第一根不相對長或比較窗不足時不成立。', '價格連續性受公司行動干擾時不評分。'],
    limitations: commonLimitations,
    lessonLinks: MULTI_LESSON,
    matcher: mvpMatcher(
      'three-candle-star',
      23,
      75,
      { ruleId: 'bullish-three-candle-star-midpoint', teachingLabel: '相對長下跌第一根、小實體或十字第二根與穿越中點的上漲第三根', parameters: { direction: 'bullish', parentPercentile: 0.75, comparisonWindow: 20, requiresMidpoint: true } },
      { ruleId: 'prior-structure-falling', teachingLabel: '前段結構可辨識為下行背景', parameters: { expected: 'falling' } },
      { ruleId: 'separation-zone-and-volume-context', teachingLabel: '第二根分離口徑、位置與量價可供核對', parameters: { needs: 'separation-zone-volume' } },
      { ruleId: 'star-window-action-or-comparison-unavailable', teachingLabel: '公司行動或相對實體比較窗不足時不評分', parameters: { requiresPriceContinuity: true, minimumPriorBodies: 20 } },
    ),
  }),
  card({
    id: 'evening-star',
    nameZhTw: '暮星形',
    nameEn: 'Evening star',
    aliases: ['暮星'],
    category: '雙根與三根組合',
    matchSupport: 'mvp',
    sourceRow: '暮星形',
    sourceNotes: sourceNote('雙根與三根組合', '暮星形'),
    oneSentenceMeaning: '相對長上漲實體、小實體或十字、以及收盤跌破第一根中點的下跌第三根，構成三根條件。',
    observableDefinition: '第一根為相對長上漲實體，第二根為小實體或十字，第三根下跌且收盤穿越第一根實體中點。',
    dataRequirements: ['至少 23 根完成 K 線', '第一根前 20 根比較窗', '三根完整 OHLC 與公司行動資料'],
    background: ['核對上行背景、第二根實體分離口徑、位置與確認。', '公司行動影響價格連續性時不能硬判缺口。'],
    commonMisreads: ['把任意三根下跌組合視為暮星。', '忽略第一根相對長與第三根中點穿越。'],
    invalidationGuidance: ['缺少中點穿越、第一根不相對長或比較窗不足時不成立。', '價格連續性受公司行動干擾時不評分。'],
    limitations: commonLimitations,
    lessonLinks: MULTI_LESSON,
    matcher: mvpMatcher(
      'three-candle-star',
      23,
      75,
      { ruleId: 'bearish-three-candle-star-midpoint', teachingLabel: '相對長上漲第一根、小實體或十字第二根與穿越中點的下跌第三根', parameters: { direction: 'bearish', parentPercentile: 0.75, comparisonWindow: 20, requiresMidpoint: true } },
      { ruleId: 'prior-structure-rising', teachingLabel: '前段結構可辨識為上行背景', parameters: { expected: 'rising' } },
      { ruleId: 'separation-zone-and-volume-context', teachingLabel: '第二根分離口徑、位置與量價可供核對', parameters: { needs: 'separation-zone-volume' } },
      { ruleId: 'star-window-action-or-comparison-unavailable', teachingLabel: '公司行動或相對實體比較窗不足時不評分', parameters: { requiresPriceContinuity: true, minimumPriorBodies: 20 } },
    ),
  }),
  card({
    id: 'three-advancing-candles',
    nameZhTw: '連續三根推進',
    nameEn: 'Three advancing candles',
    aliases: ['三根推進', '三根上推'],
    category: '雙根與三根組合',
    matchSupport: 'mvp',
    sourceRow: '連續三根推進',
    sourceNotes: sourceNote('雙根與三根組合', '連續三根推進'),
    oneSentenceMeaning: '三根同方向非零實體、收盤依序墊高，且後兩根開盤與前根實體關係符合容忍值。',
    observableDefinition: '三根皆為同方向非零實體，收盤依序墊高；後兩根開盤在前根實體內或相距不超過一個比較單位。',
    dataRequirements: ['至少三根完成 K 線', '每根非零實體', '適用比較單位'],
    background: ['核對前段結構、位置、量價比較窗與可用價格空間。', '觸發距離不能和失效距離混在一起。'],
    commonMisreads: ['三根同色就追價。', '忽略收盤順序與開盤關係。'],
    invalidationGuidance: ['收盤未依序墊高、開盤關係不符或 K 線未完成時不成立。', '資料在右端不足時不補完推論。'],
    limitations: commonLimitations,
    lessonLinks: MULTI_LESSON,
    matcher: mvpMatcher(
      'three-candle-sequence',
      3,
      70,
      { ruleId: 'three-bullish-directional-sequence', teachingLabel: '三根同方向非零實體、收盤依序墊高且開盤關係符合一個比較單位容忍', parameters: { direction: 'bullish', maximumOpenGapUnits: 1, requiresIncreasingCloses: true } },
      { ruleId: 'prior-structure-recorded', teachingLabel: '前段結構與位置可供核對', parameters: { expected: 'recorded' } },
      { ruleId: 'volume-and-price-space-context', teachingLabel: '量價比較窗與可用價格空間可供核對', parameters: { needs: 'volume-price-space' } },
      { ruleId: 'right-edge-or-unit-unavailable', teachingLabel: '右端資料或比較單位不足時不評分', parameters: { requiresComparisonUnit: true } },
    ),
  }),
  card({
    id: 'three-falling-candles',
    nameZhTw: '連續三根下跌',
    nameEn: 'Three falling candles',
    aliases: ['三根下跌', '三根下推'],
    category: '雙根與三根組合',
    matchSupport: 'mvp',
    sourceRow: '連續三根下跌',
    sourceNotes: sourceNote('雙根與三根組合', '連續三根下跌'),
    oneSentenceMeaning: '三根同方向非零實體、收盤依序降低，且後兩根開盤與前根實體關係符合容忍值。',
    observableDefinition: '三根皆為同方向非零實體，收盤依序降低；後兩根開盤在前根實體內或相距不超過一個比較單位。',
    dataRequirements: ['至少三根完成 K 線', '每根非零實體', '適用比較單位'],
    background: ['核對前段結構、位置、量價比較窗與可用價格空間。', '右端資料未完成時保留不確定性。'],
    commonMisreads: ['看到三根下跌就把後續當成定論。', '忽略收盤順序與開盤關係。'],
    invalidationGuidance: ['收盤未依序降低、開盤關係不符或 K 線未完成時不成立。', '資料在右端不足時不補完推論。'],
    limitations: commonLimitations,
    lessonLinks: MULTI_LESSON,
    matcher: mvpMatcher(
      'three-candle-sequence',
      3,
      70,
      { ruleId: 'three-bearish-directional-sequence', teachingLabel: '三根同方向非零實體、收盤依序降低且開盤關係符合一個比較單位容忍', parameters: { direction: 'bearish', maximumOpenGapUnits: 1, requiresDecreasingCloses: true } },
      { ruleId: 'prior-structure-recorded', teachingLabel: '前段結構與位置可供核對', parameters: { expected: 'recorded' } },
      { ruleId: 'volume-and-price-space-context', teachingLabel: '量價比較窗與可用價格空間可供核對', parameters: { needs: 'volume-price-space' } },
      { ruleId: 'right-edge-or-unit-unavailable', teachingLabel: '右端資料或比較單位不足時不評分', parameters: { requiresComparisonUnit: true } },
    ),
  }),
  ...TALIB_BATCH_1_CARD_DEFINITIONS.map(card),
  ...TALIB_BATCH_2_CARD_DEFINITIONS.map(card),
  ...TALIB_BATCH_3_CARD_DEFINITIONS.map(card),
  ...TALIB_BATCH_4_CARD_DEFINITIONS.map(card),
  card({
    id: 'range',
    nameZhTw: '區間',
    nameEn: 'Range',
    aliases: ['盤整區間', '支撐壓力區'],
    category: '結構型態',
    matchSupport: 'catalog-only',
    automationSupport: 'structure',
    sourceRow: '區間',
    sourceNotes: sourceNote('結構型態', '區間'),
    oneSentenceMeaning: '上、下反應區各至少兩次可辨識反應時，以價格範圍而非一條精確線描述區間。',
    observableDefinition: '上、下反應區各至少兩次可辨識反應，邊界以預先定義的價格範圍表示。',
    dataRequirements: ['固定週期', '事前固定的 k 值與反應錨點', '區域寬度與市場狀態'],
    background: ['說明區間前的結構與反應錨點選取規則。', '以區域寬度表達不確定性。'],
    commonMisreads: ['畫一條精確線就稱支撐或壓力。', '只憑單側錨點就命名區間。'],
    invalidationGuidance: ['只有單側錨點、反覆穿越或公司行動未排除時，不能視為穩定區間。', '自動結果仍須核對錨點、邊界與資料連續性。'],
    limitations: [...commonLimitations, '結構引擎以固定轉折與區域門檻選點；視覺上相似但未過門檻時不會補入候選。'],
    lessonLinks: STRUCTURE_LESSON,
  }),
  card({
    id: 'triangle-consolidation',
    nameZhTw: '三角形整理',
    nameEn: 'Triangle consolidation',
    aliases: ['收斂三角形', '三角整理'],
    category: '結構型態',
    matchSupport: 'catalog-only',
    automationSupport: 'structure',
    sourceRow: '三角形整理',
    sourceNotes: sourceNote('結構型態', '三角形整理'),
    oneSentenceMeaning: '兩側邊界按相同規則選出並逐步收斂時，才可討論三角形整理。',
    observableDefinition: '兩側邊界逐步收斂，且兩邊各至少有兩個以同一規則選出的反應錨點。',
    dataRequirements: ['固定錨點規則', '同一週期的兩側反應點', '前段結構、量價與確認口徑'],
    background: ['先說明前段結構與兩條邊界的共同選點規則。', '確認口徑與觀察週期需要固定。'],
    commonMisreads: ['兩條斜線相交就必有突破。', '一側使用任意延伸線。'],
    invalidationGuidance: ['兩側錨點不足、週期混用或收斂未成立時不成立。', '自動結果仍須核對兩側錨點、壓縮比例與交點位置。'],
    limitations: [...commonLimitations, '結構線的選點會改變結論；本站只依固定且版本化規則列出候選。'],
    lessonLinks: STRUCTURE_LESSON,
  }),
  card({
    id: 'flag-consolidation',
    nameZhTw: '旗形整理',
    nameEn: 'Flag consolidation',
    aliases: ['旗形', '短整理旗形'],
    category: '結構型態',
    matchSupport: 'catalog-only',
    automationSupport: 'structure',
    sourceRow: '旗形整理',
    sourceNotes: sourceNote('結構型態', '旗形整理'),
    oneSentenceMeaning: '方向性移動後的短整理若重疊較多、振幅較小且方向相反或橫向，才是可核對的旗形描述。',
    observableDefinition: '先有方向性移動，後出現重疊較多、振幅較小且方向相反或橫向的短整理。',
    dataRequirements: ['前段方向性移動的比較窗', '整理振幅與重疊程度', '同一週期的結構資料'],
    background: ['前段方向性移動與整理幅度需使用同一比較窗。', '確認條件不能被省略。'],
    commonMisreads: ['一段斜線就叫旗形。', '把名稱直接延伸成後續必然延續。'],
    invalidationGuidance: ['前段不清楚、整理幅度不小或錨點任意時不成立。', '自動結果仍須核對旗桿與整理通道是否使用同一週期。'],
    limitations: [...commonLimitations, '短整理以固定振幅、重疊與方向門檻量化，不把任意斜線補成旗形。'],
    lessonLinks: STRUCTURE_LESSON,
  }),
  card({
    id: 'double-top',
    nameZhTw: '雙重頂',
    nameEn: 'Double top',
    aliases: ['雙頂'],
    category: '結構型態',
    matchSupport: 'catalog-only',
    automationSupport: 'structure',
    sourceRow: '雙重頂',
    sourceNotes: sourceNote('結構型態', '雙重頂'),
    oneSentenceMeaning: '兩個局部高點位於同一關鍵區域、其間有可辨識波谷時，才是雙重頂候選。',
    observableDefinition: '兩個局部高點落在同一關鍵區域，中間有可辨識波谷，並需另定收盤離開波谷區的確認。',
    dataRequirements: ['區域寬度', '局部高點與中間波谷規則', '固定週期與確認條件'],
    background: ['先固定關鍵區的寬度與時間週期。', '確認條件應與形狀分開記錄。'],
    commonMisreads: ['兩次碰高就預設下跌。', '用事後畫出的精確水平線取代區域。'],
    invalidationGuidance: ['高點不在同一區域、波谷未定義或未收盤離開波谷區時，不能確認。', '自動結果仍須核對兩峰距離、容忍區與頸線。'],
    limitations: [...commonLimitations, '局部高點與區域寬度有選點依賴；本站以固定 ATR 門檻列出候選。'],
    lessonLinks: STRUCTURE_LESSON,
  }),
  card({
    id: 'double-bottom',
    nameZhTw: '雙重底',
    nameEn: 'Double bottom',
    aliases: ['雙底'],
    category: '結構型態',
    matchSupport: 'catalog-only',
    automationSupport: 'structure',
    sourceRow: '雙重底',
    sourceNotes: sourceNote('結構型態', '雙重底'),
    oneSentenceMeaning: '兩個局部低點位於同一關鍵區域、其間有可辨識波峰時，才是雙重底候選。',
    observableDefinition: '兩個局部低點落在同一關鍵區域，中間有可辨識波峰，並需另定收盤離開波峰區的確認。',
    dataRequirements: ['區域寬度', '局部低點與中間波峰規則', '固定週期與確認條件'],
    background: ['先固定關鍵區的寬度與時間週期。', '確認條件應與形狀分開記錄。'],
    commonMisreads: ['兩次碰低就預設上漲。', '忽略中間波峰與收盤確認。'],
    invalidationGuidance: ['低點不在同一區域、波峰未定義或未收盤離開波峰區時，不能確認。', '自動結果仍須核對兩谷距離、容忍區與頸線。'],
    limitations: [...commonLimitations, '局部低點與區域寬度有選點依賴；本站以固定 ATR 門檻列出候選。'],
    lessonLinks: STRUCTURE_LESSON,
  }),
  card({
    id: 'head-and-shoulders-top',
    nameZhTw: '頭肩頂',
    nameEn: 'Head and shoulders top',
    aliases: ['頭肩頂形'],
    category: '結構型態',
    matchSupport: 'catalog-only',
    automationSupport: 'structure',
    sourceRow: '頭肩頂／頭肩底',
    sourceNotes: sourceNote('結構型態', '頭肩頂／頭肩底'),
    oneSentenceMeaning: '三個局部高點中，中間頭部高於兩肩，兩肩與頸線都必須用區域與錨點規則描述。',
    observableDefinition: '三個局部高點中間頭部高於兩肩；兩肩與頸線均為依固定錨點畫出的區域。',
    dataRequirements: ['三個局部高點與頸線錨點', '區域寬度', '固定確認口徑'],
    background: ['確認肩部、頭部與頸線是否由同一選點規則決定。', '量價與收盤離開頸線區應另行核對。'],
    commonMisreads: ['對稱外觀比 OHLC 與錨點更重要。', '看到圖像相似就忽略頸線區。'],
    invalidationGuidance: ['任一肩部、頭部或頸線需要任意選點時不成立。', '收盤尚未離開頸線區時，不能把確認視為已發生。'],
    limitations: [...commonLimitations, '結構的視覺相似不足以取代可重現的肩部、頭部與頸線錨點規則。'],
    lessonLinks: STRUCTURE_LESSON,
  }),
  card({
    id: 'head-and-shoulders-bottom',
    nameZhTw: '頭肩底',
    nameEn: 'Head and shoulders bottom',
    aliases: ['倒頭肩', '頭肩底形'],
    category: '結構型態',
    matchSupport: 'catalog-only',
    automationSupport: 'structure',
    sourceRow: '頭肩頂／頭肩底',
    sourceNotes: sourceNote('結構型態', '頭肩頂／頭肩底'),
    oneSentenceMeaning: '三個局部低點中，中間頭部低於兩肩，兩肩與頸線都必須用區域與錨點規則描述。',
    observableDefinition: '三個局部低點中間頭部低於兩肩；兩肩與頸線均為依固定錨點畫出的區域。',
    dataRequirements: ['三個局部低點與頸線錨點', '區域寬度', '固定確認口徑'],
    background: ['確認肩部、頭部與頸線是否由同一選點規則決定。', '量價與收盤離開頸線區應另行核對。'],
    commonMisreads: ['對稱外觀比 OHLC 與錨點更重要。', '看到圖像相似就忽略頸線區。'],
    invalidationGuidance: ['任一肩部、頭部或頸線需要任意選點時不成立。', '收盤尚未離開頸線區時，不能把確認視為已發生。'],
    limitations: [...commonLimitations, '結構的視覺相似不足以取代可重現的肩部、頭部與頸線錨點規則。'],
    lessonLinks: STRUCTURE_LESSON,
  }),
  card({
    id: 'false-breakout',
    nameZhTw: '假突破',
    nameEn: 'False breakout',
    aliases: ['突破失敗', '假跌破'],
    category: '結構型態',
    matchSupport: 'catalog-only',
    automationSupport: 'structure',
    sourceRow: '假突破',
    sourceNotes: sourceNote('結構型態', '假突破'),
    oneSentenceMeaning: '事前邊界與離開口徑已寫定後，價格短暫離開又以收盤回到原區域或未守住條件，才可稱為假突破。',
    observableDefinition: '事前定義區域與離開口徑；價格短暫離開後以收盤回到原區域，或未守住預先條件。',
    dataRequirements: ['事前定義的區域與收盤規則', '固定觸發與失效條件', '完整 OHLC'],
    background: ['邊界、收盤規則與事件時間必須在事前記錄。', '需要把盤中穿越與收盤離開分開。'],
    commonMisreads: ['所有回落都叫假突破。', '事後才畫邊界。'],
    invalidationGuidance: ['只看盤中穿越或缺少回收口徑時不成立。', '自動結果只使用事前已建立的邊界，不事後移線追圖。'],
    limitations: [...commonLimitations, '假突破需要事前可審核的邊界、有效離開與限期返回，缺一不可。'],
    lessonLinks: STRUCTURE_LESSON,
  }),
  ...ADDITIONAL_STRUCTURE_CARD_DEFINITIONS.map(card),
  card({
    id: 'volume-expansion',
    nameZhTw: '量能擴張',
    nameEn: 'Volume expansion',
    aliases: ['放量'],
    category: '量價、流動性與守門',
    matchSupport: 'catalog-only',
    sourceRow: '量能擴張／量能收縮',
    sourceNotes: sourceNote('量價、流動性與失敗訊號', '量能擴張／量能收縮'),
    oneSentenceMeaning: '目標日成交量高於事前固定的同標的、同週期回看窗統計量時，描述為量能擴張。',
    observableDefinition: '目標日成交量高於事前固定的同標的、同週期、已完成回看窗統計量；目標日不放入比較窗。',
    dataRequirements: ['目標日成交量', '事前固定回看窗與統計量', '相同標的、週期與資料單位'],
    background: ['同時記錄位置與價格結果。', '比較窗需要能重現。'],
    commonMisreads: ['用單一量柱宣告方向。', '把目標日放入比較窗拉高基準。'],
    invalidationGuidance: ['窗長或統計量未寫、資料單位不一致時不能命名。', '第一版不把量能卡列為自動候選。'],
    limitations: [...commonLimitations, '量能只是一項可核對資料，第一版仍以短窗 K 線幾何卡作自動比對。'],
    lessonLinks: VOLUME_LESSON,
  }),
  card({
    id: 'volume-contraction',
    nameZhTw: '量能收縮',
    nameEn: 'Volume contraction',
    aliases: ['縮量'],
    category: '量價、流動性與守門',
    matchSupport: 'catalog-only',
    sourceRow: '量能擴張／量能收縮',
    sourceNotes: sourceNote('量價、流動性與失敗訊號', '量能擴張／量能收縮'),
    oneSentenceMeaning: '目標日成交量低於事前固定的同標的、同週期回看窗統計量時，描述為量能收縮。',
    observableDefinition: '目標日成交量低於事前固定的同標的、同週期、已完成回看窗統計量；目標日不放入比較窗。',
    dataRequirements: ['目標日成交量', '事前固定回看窗與統計量', '相同標的、週期與資料單位'],
    background: ['同時記錄位置與價格結果。', '比較窗需要能重現。'],
    commonMisreads: ['用單一量柱宣告方向。', '把目標日放入比較窗拉低基準。'],
    invalidationGuidance: ['窗長或統計量未寫、資料單位不一致時不能命名。', '第一版不把量能卡列為自動候選。'],
    limitations: [...commonLimitations, '量能只是一項可核對資料，第一版仍以短窗 K 線幾何卡作自動比對。'],
    lessonLinks: VOLUME_LESSON,
  }),
  card({
    id: 'effort-vs-result',
    nameZhTw: '努力與結果',
    nameEn: 'Effort versus result',
    aliases: ['量價努力結果'],
    category: '量價、流動性與守門',
    matchSupport: 'catalog-only',
    sourceRow: '努力與結果',
    sourceNotes: sourceNote('量價、流動性與失敗訊號', '努力與結果'),
    oneSentenceMeaning: '把成交量與實體、日內範圍、收盤位置或區域穿越並列，協助讀者描述觀察配對。',
    observableDefinition: '同時記錄成交量與實體、日內範圍、收盤位置或區域穿越，並使用相同口徑比較窗。',
    dataRequirements: ['成交量與 OHLC', '相同口徑比較窗', '關鍵區域與時間週期'],
    background: ['區分圖表觀察與參與者意圖的推測。', '以可重現比較窗保留量價脈絡。'],
    commonMisreads: ['高量必然等於吸收、出貨或反轉。', '把觀察配對擴寫成因果關係。'],
    invalidationGuidance: ['比較窗或資料單位不同時不可比。', '第一版不把這個描述性卡片假裝成可獨立比對的型態。'],
    limitations: [...commonLimitations, '只有日 OHLCV 不能證明參與者意圖，第一版不參與自動比對。'],
    lessonLinks: VOLUME_LESSON,
  }),
  card({
    id: 'volume-climax-risk',
    nameZhTw: '量能高潮風險',
    nameEn: 'Volume climax risk',
    aliases: ['高量大幅日'],
    category: '量價、流動性與守門',
    matchSupport: 'catalog-only',
    sourceRow: '量能高潮風險',
    sourceNotes: sourceNote('量價、流動性與失敗訊號', '量能高潮風險'),
    oneSentenceMeaning: '相對高量與相對大範圍同時出現時，列為需要額外驗證的風險假設。',
    observableDefinition: '相對高量與相對大範圍同時出現，且比較窗、位置與公司行動資料都已寫明。',
    dataRequirements: ['成交量與範圍比較窗', '位置與公司行動資料', '後續觸發與失效條件'],
    background: ['先核對相對高量和相對大範圍的固定比較窗。', '把它視為增加驗證需求，而非結論。'],
    commonMisreads: ['把高量大幅日當成最高或最低點。', '忽略事件與價格模式。'],
    invalidationGuidance: ['比較窗未寫或公司行動未核對時不可用。', '第一版不把風險假設列為自動候選。'],
    limitations: [...commonLimitations, '高量大幅日可由許多不同情境造成，第一版不參與自動比對。'],
    lessonLinks: VOLUME_LESSON,
  }),
  card({
    id: 'low-liquidity-distortion',
    nameZhTw: '低流動性扭曲',
    nameEn: 'Low-liquidity distortion',
    aliases: ['流動性不足', '價差扭曲'],
    category: '量價、流動性與守門',
    matchSupport: 'guardrail',
    sourceRow: '低流動性扭曲',
    sourceNotes: sourceNote('量價、流動性與失敗訊號', '低流動性扭曲'),
    oneSentenceMeaning: '寬價差、有限深度、成交稀疏、跳價或成交衝擊可能扭曲 K 線形狀，應先檢查可成交性。',
    observableDefinition: '可見寬價差、有限深度、成交稀疏、跳價、成交衝擊，或這些必要資料缺失。',
    dataRequirements: ['價差', '委託簿深度', '成交頻率與預計下單量', '滑價或成交衝擊資料'],
    background: ['先衡量可成交性而非只看日成交量。', '把資料缺失列為不能下結論的理由。'],
    commonMisreads: ['把日成交量當成完整流動性度量。', '忽略下單量對成交衝擊的影響。'],
    invalidationGuidance: ['只有日 OHLCV 而沒有可成交性資料時，不能可靠判定。', '第一版必須保留為守門提醒，不可自動命名。'],
    limitations: [...commonLimitations, '第一版資料沒有完整價差、深度與成交衝擊，不能可靠自動比對。'],
    lessonLinks: VOLUME_LESSON,
    guardrail: {
      title: '守門提醒：日 OHLCV 不足以衡量流動性',
      whyNotInMvp: '缺少價差、深度、成交頻率與成交衝擊資料，日 K 的形狀可能受到扭曲。',
      readerAction: '補看報價、深度與預計下單量；必要欄位缺失時，把情境標為不交易。',
    },
  }),
  card({
    id: 'failed-signal',
    nameZhTw: '失敗訊號',
    nameEn: 'Failed signal',
    aliases: ['訊號失效'],
    category: '量價、流動性與守門',
    matchSupport: 'guardrail',
    sourceRow: '失敗訊號',
    sourceNotes: sourceNote('量價、流動性與失敗訊號', '失敗訊號'),
    oneSentenceMeaning: '事前觸發條件未出現，或價格觸及事前寫好的失效條件離開原情境時，記錄為失敗訊號。',
    observableDefinition: '事前觸發條件未出現，或發生事前寫好的失效條件後離開原情境；不可事後改寫規則。',
    dataRequirements: ['事前觸發條件', '事前失效條件', '風險與資料品質紀錄'],
    background: ['每次判讀前先寫下觸發、失效與放棄條件。', '失敗樣本與成功樣本都要保留。'],
    commonMisreads: ['先看結果再命名成功或失敗。', '只挑成功樣本忽略失效條件。'],
    invalidationGuidance: ['規則事後改寫時，不能把結果稱為可驗證的失敗訊號。', '第一版不把守門條件轉成圖形候選。'],
    limitations: [...commonLimitations, '失敗訊號依賴事前計畫與後續觀察，不是可由單一日 K 可靠自動命名的型態。'],
    lessonLinks: VOLUME_LESSON,
    guardrail: {
      title: '守門提醒：先寫失效，才有可檢查的訊號',
      whyNotInMvp: '是否失效需要事前觸發、失效與風險紀錄，不能由當下短窗日 K 單獨推得。',
      readerAction: '回到情境計畫，核對原先寫下的觸發與失效條件，不要用結果改名。',
    },
  }),
  card({
    id: 'insufficient-evidence',
    nameZhTw: '證據不足',
    nameEn: 'Insufficient evidence',
    aliases: ['資料不足', '不可判讀'],
    category: '量價、流動性與守門',
    matchSupport: 'guardrail',
    sourceRow: '證據不足',
    sourceNotes: sourceNote('量價、流動性與失敗訊號', '證據不足'),
    oneSentenceMeaning: '比較窗、公司行動、價差、深度、成交衝擊或資料品質的必要欄位缺失時，證據不足本身就是答案。',
    observableDefinition: '比較窗、公司行動、價差、深度、成交衝擊或資料品質中的必要欄位缺失，並明示其影響。',
    dataRequirements: ['各型態所需的完整欄位', '公司行動與資料品質來源', '可追溯的缺失原因'],
    background: ['說明缺少什麼、會影響哪個條件，以及何時不交易。', '不要用猜測補上缺失資料。'],
    commonMisreads: ['覺得「不知道」不是答案。', '把缺資料的條件以低分補入候選。'],
    invalidationGuidance: ['必要欄位缺失時停止該判讀，不以其他條件補分。', '第一版應回傳證據不足，而非自動命名。'],
    limitations: [...commonLimitations, '資料缺失時不能以外觀或預設值補齊，這張卡永遠作為守門提醒。'],
    lessonLinks: VOLUME_LESSON,
    guardrail: {
      title: '守門提醒：缺少必要欄位時停止判讀',
      whyNotInMvp: '證據不足是分析結果的保護條件，不是要和其他卡競爭分數的圖形型態。',
      readerAction: '列出缺失欄位與受影響條件；未補齊可追溯資料前，不把情境寫成候選。',
    },
  }),
] as const;

const CARD_BY_ID: ReadonlyMap<PatternCardId, PatternCardDefinition> = new Map(
  PATTERN_CARDS.map((pattern) => [pattern.id, pattern]),
);

function validateCatalog(cards: readonly PatternCardDefinition[]): void {
  if (cards.length !== PATTERN_CARD_IDS.length) {
    throw new Error('型態卡清冊數量不正確');
  }

  if (new Set(cards.map((pattern) => pattern.id)).size !== PATTERN_CARD_IDS.length) {
    throw new Error('型態卡清冊有重複識別碼');
  }

  const mvpCards = cards.filter((pattern) => pattern.matchSupport === 'mvp');
  if (mvpCards.length !== 17) {
    throw new Error('第一版可比對型態卡數量不正確');
  }

  for (const pattern of mvpCards) {
    const matcher = pattern.matcher;
    if (!matcher || matcher.minimumBars < 1 || matcher.minimumScore < 60 || matcher.minimumScore > 75) {
      throw new Error(`型態卡 ${pattern.id} 的 matcher 設定不完整`);
    }

    const weightFor = (group: PatternRuleBinding['group']): number =>
      matcher.rules.filter((rule) => rule.group === group).reduce((total, rule) => total + rule.weight, 0);

    if (weightFor('required') !== 50 || weightFor('context') !== 30 || weightFor('supporting') !== 20) {
      throw new Error(`型態卡 ${pattern.id} 的規則權重不正確`);
    }

    if (matcher.rules.filter((rule) => rule.group === 'invalidating').some((rule) => rule.weight !== 0)) {
      throw new Error(`型態卡 ${pattern.id} 的失效規則不可計分`);
    }

    if (matcher.rules.some((rule) => !hasValidRuleBindingParameters(rule))) {
      throw new Error(`型態卡 ${pattern.id} 的規則參數不符合資料契約`);
    }
  }
}

validateCatalog(PATTERN_CARDS);

/** 以正規 ID 取得教學卡；未知 ID 必須明確失敗，避免 UI 與 matcher 各自猜測。 */
export function getPatternCard(id: PatternCardId): PatternCardDefinition {
  const pattern = CARD_BY_ID.get(id);
  if (!pattern) {
    throw new Error(`找不到型態卡：${id}`);
  }

  return pattern;
}

/** 由集合投影正規卡片物件，不建立內容複本。 */
export function getPatternCardsByCollection(
  collection: PatternCollectionId,
): readonly PatternCardDefinition[] {
  return PATTERN_CARDS.filter((pattern) => pattern.collections.includes(collection));
}

/** 供篩選 UI 使用的固定顯示順序。 */
export const PATTERN_CATEGORIES: readonly PatternCategory[] = [
  '單根與描述型',
  '雙根與三根組合',
  '進階 K 棒組合',
  '結構型態',
  '量價、流動性與守門',
] as const;

/** 供篩選 UI 使用的固定顯示順序。 */
export const MATCH_SUPPORTS: readonly MatchSupport[] = ['mvp', 'catalog-only', 'guardrail'] as const;
export const AUTOMATION_SUPPORTS: readonly AutomationSupport[] = [
  'short-window',
  'structure',
  'teaching-only',
  'guardrail',
] as const;
