import type { PatternCardInput } from './types';

const STRUCTURE_LESSON = ['/chapters/11-consolidation-reversal-continuation-patterns'] as const;

const CFA_SOURCE = 'CFA Institute Member Guide｜反轉型態、三角形、矩形與三角旗形。';
const CMT_GUIDE_SOURCE = 'CMT Association 2026 Program Guide｜classical chart patterns、三重頂、上升楔形與圓弧頂。';
const CMT_LOS_SOURCE = 'CMT Association Level II Learning Objectives｜三角形、三重頂底、圓弧與三角旗形。';
const LO_SOURCE = 'Lo、Mamaysky、Wang｜局部極值規則涵蓋三角形、矩形與擴散頂底。';
const RESEARCH_SOURCE = (row: string): string => `本站研究清單｜第二階段常見擴充｜${row}。`;
const ROUNDING_TOP_RESEARCH_SOURCE = '本站研究清單｜第一階段自動辨識核心｜圓弧頂。';

const STRUCTURE_LIMITATIONS = [
  '型態名稱只協助整理可觀察條件，不構成未來價格保證或任何交易建議。',
  '轉折點、區域寬度與邊界必須使用事前固定的同一規則，不能為了貼合圖形事後移動。',
  '本站目前只提供教學比對；在規則族、正反案例與誤判邊界完成前，不參與自動排行。',
] as const;

type StructureCardInput = Omit<PatternCardInput, 'slug' | 'category' | 'matchSupport' | 'lessonLinks'>;

function structureCard(definition: StructureCardInput): PatternCardInput {
  return {
    ...definition,
    category: '結構型態',
    matchSupport: 'catalog-only',
    lessonLinks: STRUCTURE_LESSON,
  };
}

/** 研究清單第二階段，以及首批尚缺的圓弧頂教學定義。 */
export const ADDITIONAL_STRUCTURE_CARD_DEFINITIONS: readonly PatternCardInput[] = [
  structureCard({
    id: 'rounding-top',
    nameZhTw: '圓弧頂',
    nameEn: 'Rounding top',
    aliases: ['碟形頂', '圓頂'],
    sourceRow: '圓弧頂',
    sourceNotes: [ROUNDING_TOP_RESEARCH_SOURCE, CMT_GUIDE_SOURCE, CMT_LOS_SOURCE],
    oneSentenceMeaning: '價格推進斜率逐步由正轉平再轉負，形成漸進轉弱的寬弧輪廓。',
    observableDefinition: '在足夠跨度內，平滑後的價格斜率依序由上升、趨平到下降，且不是單一尖峰造成。',
    dataRequirements: ['足夠長的連續完成 K 線', '固定平滑與斜率口徑', '事前建立的支撐區或弧形基準'],
    background: ['常見於一段上升或高檔盤整後，但背景本身不能取代弧形幾何。', '成交量只作輔助核對。'],
    confirmationGuidance: ['收盤有效跌破事前建立的支撐區或弧形基準後，才把輪廓標為已確認。'],
    commonMisreads: ['要求每根價格形成完美拋物線。', '把單一尖峰後回落稱為圓弧頂。'],
    invalidationGuidance: ['斜率沒有由正轉平再轉負、輪廓主要由少數異常 K 棒造成，或價格重新站回失效區時不成立。'],
    limitations: STRUCTURE_LIMITATIONS,
  }),
  structureCard({
    id: 'rounding-bottom',
    nameZhTw: '圓弧底',
    nameEn: 'Rounding bottom',
    aliases: ['碟形底', '圓底'],
    sourceRow: '圓弧底',
    sourceNotes: [RESEARCH_SOURCE('圓弧底'), CMT_LOS_SOURCE],
    oneSentenceMeaning: '價格下行斜率逐步由負轉平再轉正，形成漸進轉強的寬弧輪廓。',
    observableDefinition: '在足夠跨度內，平滑後的價格斜率依序由下降、趨平到上升，且不是單一急跌反彈造成。',
    dataRequirements: ['足夠長的連續完成 K 線', '固定平滑與斜率口徑', '事前建立的壓力區或弧形基準'],
    background: ['常見於一段下降或低檔盤整後，但位置不能單獨完成命名。', '成交量變化需要用固定比較窗核對。'],
    confirmationGuidance: ['收盤有效突破事前建立的壓力區或弧形基準後，才把輪廓標為已確認。'],
    commonMisreads: ['把 V 型急跌反彈稱為圓弧底。', '只因價格位於低檔便補畫圓弧。'],
    invalidationGuidance: ['斜率沒有由負轉平再轉正、輪廓被少數異常 K 棒主導，或價格跌回失效區時不成立。'],
    limitations: STRUCTURE_LIMITATIONS,
  }),
  structureCard({
    id: 'triple-top',
    nameZhTw: '三重頂',
    nameEn: 'Triple top',
    aliases: ['三尊頭', '三頂'],
    sourceRow: '三重頂',
    sourceNotes: [RESEARCH_SOURCE('三重頂'), CFA_SOURCE, CMT_GUIDE_SOURCE, CMT_LOS_SOURCE],
    oneSentenceMeaning: '三個局部高點位於同一壓力區，且兩個中間波谷可用一致規則辨識。',
    observableDefinition: '三個相隔足夠距離的局部高點落在同一價格區域，中間有兩個可辨識波谷。',
    dataRequirements: ['三個高點與兩個波谷', '固定區域寬度及最小間隔', '頸線或波谷區收盤規則'],
    background: ['先確認前段上升或高檔結構。', '三次反應都要使用同一區域與轉折規則。'],
    confirmationGuidance: ['收盤有效跌破兩個波谷共同建立的頸線區後才確認；未跌破前只算形成中。'],
    commonMisreads: ['把三個任意高點連在一起。', '第三次觸及壓力區就提前宣告完成。'],
    invalidationGuidance: ['高點不在同一區域、波谷不足，或價格有效突破並守住上方壓力區時不成立。'],
    limitations: STRUCTURE_LIMITATIONS,
  }),
  structureCard({
    id: 'triple-bottom',
    nameZhTw: '三重底',
    nameEn: 'Triple bottom',
    aliases: ['三底'],
    sourceRow: '三重底',
    sourceNotes: [RESEARCH_SOURCE('三重底'), CFA_SOURCE, CMT_LOS_SOURCE],
    oneSentenceMeaning: '三個局部低點位於同一支撐區，且兩個中間波峰可用一致規則辨識。',
    observableDefinition: '三個相隔足夠距離的局部低點落在同一價格區域，中間有兩個可辨識波峰。',
    dataRequirements: ['三個低點與兩個波峰', '固定區域寬度及最小間隔', '頸線或波峰區收盤規則'],
    background: ['先確認前段下降或低檔結構。', '三次反應都要使用同一區域與轉折規則。'],
    confirmationGuidance: ['收盤有效突破兩個波峰共同建立的頸線區後才確認；未突破前只算形成中。'],
    commonMisreads: ['把三個任意低點連在一起。', '第三次觸及支撐區就提前宣告完成。'],
    invalidationGuidance: ['低點不在同一區域、波峰不足，或價格有效跌破並停留在支撐區下方時不成立。'],
    limitations: STRUCTURE_LIMITATIONS,
  }),
  structureCard({
    id: 'symmetrical-triangle',
    nameZhTw: '對稱三角形',
    nameEn: 'Symmetrical triangle',
    aliases: ['對稱三角收斂'],
    sourceRow: '對稱三角形',
    sourceNotes: [RESEARCH_SOURCE('對稱三角形'), CFA_SOURCE, CMT_LOS_SOURCE, LO_SOURCE],
    oneSentenceMeaning: '下降上緣與上升下緣同時收斂，突破前不預設離開方向。',
    observableDefinition: '至少兩個依序降低的高點與兩個依序升高的低點形成收斂邊界，多數 K 棒位於其間。',
    dataRequirements: ['兩側各至少兩個錨點', '邊界斜率與收斂率', '收盤離開邊界的固定口徑'],
    background: ['可出現在不同前段趨勢，不能只依名稱判斷用途。', '形成期間的波動範圍應逐步縮小。'],
    confirmationGuidance: ['收盤有效離開任一邊界後，才依實際突破方向標示確認。'],
    commonMisreads: ['突破前先指定多空方向。', '只畫出會相交的兩條線就稱為收斂。'],
    invalidationGuidance: ['邊界未收斂、錨點不足、多數 K 棒不在邊界內，或突破後立即收回時不成立或轉為假突破觀察。'],
    limitations: STRUCTURE_LIMITATIONS,
  }),
  structureCard({
    id: 'ascending-triangle',
    nameZhTw: '上升三角形',
    nameEn: 'Ascending triangle',
    aliases: ['平頂上升三角'],
    sourceRow: '上升三角形',
    sourceNotes: [RESEARCH_SOURCE('上升三角形'), CFA_SOURCE, CMT_LOS_SOURCE, LO_SOURCE],
    oneSentenceMeaning: '近水平上緣搭配逐步墊高的下緣，仍須等待實際收盤離開邊界。',
    observableDefinition: '上方至少兩個高點位於近水平壓力區，下方至少兩個低點逐步升高並收斂。',
    dataRequirements: ['水平上緣區與上升下緣錨點', '邊界容忍值', '收盤突破或跌破口徑'],
    background: ['常被視為整理型態，但前段趨勢與可用價格空間仍須分開記錄。', '不能忽略下方邊界。'],
    confirmationGuidance: ['收盤有效離開上緣或下緣後才確認實際方向；名稱不等於必然向上。'],
    commonMisreads: ['看到低點墊高就預設向上突破。', '上緣只有單一接觸點。'],
    invalidationGuidance: ['低點未墊高、上緣不近水平、錨點不足，或價格反覆穿越兩側邊界時不成立。'],
    limitations: STRUCTURE_LIMITATIONS,
  }),
  structureCard({
    id: 'descending-triangle',
    nameZhTw: '下降三角形',
    nameEn: 'Descending triangle',
    aliases: ['平底下降三角'],
    sourceRow: '下降三角形',
    sourceNotes: [RESEARCH_SOURCE('下降三角形'), CFA_SOURCE, CMT_LOS_SOURCE, LO_SOURCE],
    oneSentenceMeaning: '近水平下緣搭配逐步降低的上緣，仍須等待實際收盤離開邊界。',
    observableDefinition: '下方至少兩個低點位於近水平支撐區，上方至少兩個高點逐步降低並收斂。',
    dataRequirements: ['水平下緣區與下降上緣錨點', '邊界容忍值', '收盤突破或跌破口徑'],
    background: ['常被視為整理型態，但前段趨勢與可用價格空間仍須分開記錄。', '不能忽略上方邊界。'],
    confirmationGuidance: ['收盤有效離開下緣或上緣後才確認實際方向；名稱不等於必然向下。'],
    commonMisreads: ['看到高點降低就預設向下跌破。', '下緣只有單一接觸點。'],
    invalidationGuidance: ['高點未降低、下緣不近水平、錨點不足，或價格反覆穿越兩側邊界時不成立。'],
    limitations: STRUCTURE_LIMITATIONS,
  }),
  structureCard({
    id: 'bullish-rectangle',
    nameZhTw: '多頭矩形',
    nameEn: 'Bullish rectangle',
    aliases: ['多頭箱型', '上升趨勢矩形'],
    sourceRow: '多頭矩形',
    sourceNotes: [RESEARCH_SOURCE('多頭矩形'), CFA_SOURCE, LO_SOURCE],
    oneSentenceMeaning: '明確上升段後，價格在近水平上下邊界間整理的矩形候選。',
    observableDefinition: '前段有可量化上升移動，之後上下邊界各至少兩次反應且多數 K 棒留在矩形區內。',
    dataRequirements: ['前段上升比較窗', '上下水平邊界與觸碰數', '收盤離開區間口徑'],
    background: ['前段方向性移動與整理必須使用同一週期。', '區分延續假設與一般無方向區間。'],
    confirmationGuidance: ['收盤有效突破上緣才確認延續情境；向下跌破則記錄不同情境，而非勉強維持多頭名稱。'],
    commonMisreads: ['只因矩形前有上漲就忽略向下跌破。', '把任意橫向波動都稱為多頭矩形。'],
    invalidationGuidance: ['前段上升不清楚、水平邊界不足，或價格有效跌破下緣時，原延續情境失效。'],
    limitations: STRUCTURE_LIMITATIONS,
  }),
  structureCard({
    id: 'bearish-rectangle',
    nameZhTw: '空頭矩形',
    nameEn: 'Bearish rectangle',
    aliases: ['空頭箱型', '下降趨勢矩形'],
    sourceRow: '空頭矩形',
    sourceNotes: [RESEARCH_SOURCE('空頭矩形'), CFA_SOURCE, LO_SOURCE],
    oneSentenceMeaning: '明確下降段後，價格在近水平上下邊界間整理的矩形候選。',
    observableDefinition: '前段有可量化下降移動，之後上下邊界各至少兩次反應且多數 K 棒留在矩形區內。',
    dataRequirements: ['前段下降比較窗', '上下水平邊界與觸碰數', '收盤離開區間口徑'],
    background: ['前段方向性移動與整理必須使用同一週期。', '區分延續假設與一般無方向區間。'],
    confirmationGuidance: ['收盤有效跌破下緣才確認延續情境；向上突破則記錄不同情境，而非勉強維持空頭名稱。'],
    commonMisreads: ['只因矩形前有下跌就忽略向上突破。', '把任意橫向波動都稱為空頭矩形。'],
    invalidationGuidance: ['前段下降不清楚、水平邊界不足，或價格有效突破上緣時，原延續情境失效。'],
    limitations: STRUCTURE_LIMITATIONS,
  }),
  structureCard({
    id: 'pennant',
    nameZhTw: '三角旗形',
    nameEn: 'Pennant',
    aliases: ['尖旗形'],
    sourceRow: '三角旗形',
    sourceNotes: [RESEARCH_SOURCE('三角旗形'), CFA_SOURCE, CMT_LOS_SOURCE],
    oneSentenceMeaning: '明確方向性移動後，出現較短、較小且兩側收斂的整理區。',
    observableDefinition: '先有可量化旗桿，後有相對短小的收斂整理，整理幅度明顯小於旗桿移動。',
    dataRequirements: ['旗桿起訖與幅度', '收斂整理錨點', '整理長度及突破口徑'],
    background: ['旗桿與整理使用同一週期及價格模式。', '與沒有旗桿背景的對稱三角形分開。'],
    confirmationGuidance: ['收盤沿旗桿方向有效離開整理邊界才確認延續情境；反向離開需另作失效或新情境。'],
    commonMisreads: ['任何小三角形都叫三角旗。', '忽略旗桿與整理幅度比例。'],
    invalidationGuidance: ['旗桿不清楚、整理過長或過寬、邊界不收斂，或反向有效突破時原情境失效。'],
    limitations: STRUCTURE_LIMITATIONS,
  }),
  structureCard({
    id: 'rising-wedge',
    nameZhTw: '上升楔形',
    nameEn: 'Rising wedge',
    aliases: ['上升楔型'],
    sourceRow: '上升楔形',
    sourceNotes: [RESEARCH_SOURCE('上升楔形'), CMT_GUIDE_SOURCE],
    oneSentenceMeaning: '上下邊界都向上，但下緣上升較快而使價格範圍逐步收斂。',
    observableDefinition: '至少兩個高點與兩個低點都逐步升高，下方邊界斜率大於上方邊界且兩者收斂。',
    dataRequirements: ['上下邊界各至少兩個錨點', '斜率與收斂率', '收盤離開邊界口徑'],
    background: ['可以出現在不同前段趨勢，不以名稱直接指定結果。', '成交量縮減只是輔助，不是必要幾何。'],
    confirmationGuidance: ['收盤有效離開任一邊界後才依實際方向確認；向下離開是常見用法但不是保證。'],
    commonMisreads: ['把所有上升通道稱為楔形。', '只因名稱便提前指定向下結果。'],
    invalidationGuidance: ['上下邊界近乎平行、沒有收斂、錨點不足，或離開後立即回到楔形內時不成立或需重評。'],
    limitations: STRUCTURE_LIMITATIONS,
  }),
  structureCard({
    id: 'falling-wedge',
    nameZhTw: '下降楔形',
    nameEn: 'Falling wedge',
    aliases: ['下降楔型'],
    sourceRow: '下降楔形',
    sourceNotes: [RESEARCH_SOURCE('下降楔形')],
    oneSentenceMeaning: '上下邊界都向下，但上緣下降較快而使價格範圍逐步收斂。',
    observableDefinition: '至少兩個高點與兩個低點都逐步降低，上方邊界下降斜率絕對值大於下方邊界且兩者收斂。',
    dataRequirements: ['上下邊界各至少兩個錨點', '斜率與收斂率', '收盤離開邊界口徑'],
    background: ['可以出現在不同前段趨勢，不以名稱直接指定結果。', '成交量縮減只是輔助，不是必要幾何。'],
    confirmationGuidance: ['收盤有效離開任一邊界後才依實際方向確認；向上離開是常見用法但不是保證。'],
    commonMisreads: ['把所有下降通道稱為楔形。', '只因名稱便提前指定向上結果。'],
    invalidationGuidance: ['上下邊界近乎平行、沒有收斂、錨點不足，或離開後立即回到楔形內時不成立或需重評。'],
    limitations: STRUCTURE_LIMITATIONS,
  }),
  structureCard({
    id: 'broadening-top',
    nameZhTw: '擴散頂',
    nameEn: 'Broadening top',
    aliases: ['喇叭頂', '擴大型頂部'],
    sourceRow: '擴散頂',
    sourceNotes: [RESEARCH_SOURCE('擴散頂'), LO_SOURCE],
    oneSentenceMeaning: '高檔區域的高點逐步升高、低點逐步降低，使上下邊界向外擴張。',
    observableDefinition: '至少兩個高點與兩個低點交替出現，上緣向上、下緣向下，波動範圍逐步放大。',
    dataRequirements: ['交替高低轉折點', '發散邊界與擴張率', '收盤離開或返回邊界的口徑'],
    background: ['先確認型態位於一段上升後或高檔結構。', '區分真實擴張與單一事件造成的跳空。'],
    confirmationGuidance: ['收盤有效跌破下方邊界或事前支撐區後，才確認頂部離開情境。'],
    commonMisreads: ['任何波動放大都叫擴散頂。', '忽略公司行動或單一事件跳空。'],
    invalidationGuidance: ['邊界未向外擴張、轉折未交替，或價格突破並守住上方失效區時不成立。'],
    limitations: STRUCTURE_LIMITATIONS,
  }),
  structureCard({
    id: 'broadening-bottom',
    nameZhTw: '擴散底',
    nameEn: 'Broadening bottom',
    aliases: ['喇叭底', '擴大型底部'],
    sourceRow: '擴散底',
    sourceNotes: [RESEARCH_SOURCE('擴散底'), LO_SOURCE],
    oneSentenceMeaning: '低檔區域的高點逐步升高、低點逐步降低，使上下邊界向外擴張。',
    observableDefinition: '至少兩個高點與兩個低點交替出現，上緣向上、下緣向下，波動範圍逐步放大。',
    dataRequirements: ['交替高低轉折點', '發散邊界與擴張率', '收盤離開或返回邊界的口徑'],
    background: ['先確認型態位於一段下降後或低檔結構。', '區分真實擴張與低流動性造成的跳價。'],
    confirmationGuidance: ['收盤有效突破上方邊界或事前壓力區後，才確認底部離開情境。'],
    commonMisreads: ['任何波動放大都叫擴散底。', '忽略低流動性或公司行動。'],
    invalidationGuidance: ['邊界未向外擴張、轉折未交替，或價格跌破並停留在下方失效區時不成立。'],
    limitations: STRUCTURE_LIMITATIONS,
  }),
] as const;
